### ISSUE TITLE
Not clear how to use it with Rails

### ISSUE THREAD

**Issue by bitkidd** [logdna/rails#1]
Tried to add `Rails.logger = Logdna::RailsLogger.new(apikey, { :app => appname })` in `config/environments/production.rb` and it drops an error: `NameError: uninitialized constant Logdna`

**Comment by MattChoi1** [comment]
Hi! 
I have pushed version 1.0.1 addressing this issue. 
Could you give a try once more and let me know?
Thank you!

**Comment by bitkidd** [comment]
Yeap, it now works! Thank you!
